# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20161220_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-ontop', '-modify', 'id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
