# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20161220_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='filename',
        ),
    ]
