# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_attachment_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-modify', 'id']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ontop',
            new_name='istop',
        ),
    ]
