# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20161220_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-istop', '-modify', 'id']},
        ),
    ]
