# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
