# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_attachment_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('description',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
