# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod_model', '0001_initial'),
        ('quotations', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user', models.CharField(max_length=60)),
                ('order_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('ord_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('invalid', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.FloatField()),
                ('line_memo', models.CharField(blank=True, max_length=50, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_model.ProdModel')),
                ('quotehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelquote.ModelQuote')),
            ],
        ),
    ]
