# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['emp_number']},
        ),
        migrations.AlterModelOptions(
            name='smallpart',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='people',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
