# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20160825_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('english_name', models.CharField(max_length=60)),
                ('emp_number', models.CharField(max_length=6, unique=True)),
                ('contact_ext', models.CharField(blank=True, max_length=4, null=True)),
                ('dutydate', models.DateField()),
                ('on_duty', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Job')),
            ],
            options={
                'ordering': ['-emp_number'],
            },
        ),
        migrations.RemoveField(
            model_name='people',
            name='department',
        ),
        migrations.RemoveField(
            model_name='people',
            name='job',
        ),
        migrations.RemoveField(
            model_name='people',
            name='smallpart',
        ),
        migrations.RemoveField(
            model_name='smallpart',
            name='department',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='SmallPart',
        ),
    ]
