# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20160826_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dutydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
