# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20161119_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
