# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0002_auto_20161228_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimming',
        ),
    ]
