# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0003_remove_product_dimming'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimming',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoted.DimmingOption'),
            preserve_default=False,
        ),
    ]
