# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0005_auto_20161229_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cost_twd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expired Date'),
        ),
    ]
