# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_auto_20160926_1440'),
        ('quoted', '0005_auto_20160930_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(default=datetime.datetime(2016, 10, 2, 22, 13, 9, 281209, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='quotations.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_sales',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
