# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0006_auto_20161003_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
