# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0006_auto_20161230_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generalterm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoted.GeneralTerm'),
        ),
    ]
