# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0007_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
