# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0007_order_generalterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, default='$', max_length=4, null=True),
        ),
    ]
