# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0012_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentterm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoted.PaymentTerm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='priceterm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoted.PriceTerm'),
            preserve_default=False,
        ),
    ]
