# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0013_auto_20161020_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
