# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0014_order_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimmingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
