# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0017_order_quote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quote_sales',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
