# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0018_auto_20161103_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quote_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
