# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_auto_20160926_1440'),
        ('quoted', '0020_auto_20161104_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mix_sell', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.Currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoted.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set([('product', 'currency')]),
        ),
    ]
