# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0021_auto_20161110_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-currency']},
        ),
    ]
