# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0022_auto_20161119_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cct',
            field=models.CharField(max_length=60, verbose_name='CCT'),
        ),
    ]
