# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0023_auto_20161130_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='mix_sell',
            new_name='min_sell',
        ),
        migrations.AlterField(
            model_name='product',
            name='cri',
            field=models.CharField(max_length=60, verbose_name='CRI'),
        ),
    ]
