# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0024_auto_20161130_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('product',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
