# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0025_auto_20161201_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_remark',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
