# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0028_auto_20161222_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
