# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0029_auto_20161223_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
