# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0031_auto_20161223_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Customized Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_remark',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_beam_angle',
            field=models.CharField(max_length=60, verbose_name='Beam angle'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_dimming',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoted.DimmingOption', verbose_name='Dimming'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_image',
            field=models.ImageField(blank=True, height_field='orderitem_height_field', null=True, upload_to='', verbose_name='Image', width_field='orderitem_width_field'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_lm',
            field=models.CharField(max_length=60, verbose_name='LM'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_modelname',
            field=models.CharField(max_length=60, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_name',
            field=models.CharField(max_length=60, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_option1',
            field=models.CharField(max_length=60, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_watt',
            field=models.CharField(max_length=60, verbose_name='WATT'),
        ),
    ]
