# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoted', '0032_auto_20161227_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_dimming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoted.DimmingOption', verbose_name='Dimming'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoted.DimmingOption'),
        ),
    ]
