# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('sap_no', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=36)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contect', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('faxno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
