# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('job', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('extention', models.CharField(blank=True, max_length=8, null=True)),
                ('invalid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-master'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('sap_no', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=36)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('faxno', models.CharField(blank=True, max_length=100, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
