# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=30)),
                ('prodname', models.CharField(max_length=60)),
                ('modelname', models.CharField(max_length=60)),
                ('option1', models.CharField(max_length=60)),
                ('beam_angle', models.CharField(max_length=60)),
                ('cct', models.CharField(max_length=60)),
                ('cri', models.CharField(max_length=60)),
                ('watt', models.CharField(max_length=60)),
                ('lm', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
