# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_auto_20160901_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-last_access']},
        ),
    ]
