# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotehead',
            name='order_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
