# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20160914_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetail',
            name='line_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
