# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160825_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateDesctiption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=36)),
                ('specification', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('encoding', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='catedesctiption',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Language'),
        ),
    ]
