# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160825_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
